name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.docs-changes.outputs.docs }}
      docs_added_list: ${{ steps.docs-changes.outputs.added_files }}
      docs_modified_list: ${{ steps.docs-changes.outputs.modified_files }}
      docs_deleted_list: ${{ steps.docs-changes.outputs.deleted_files }}
    
    steps:
      - name: Check changed files
        uses: dorny/paths-filter@v2
        id: docs-changes
        with:
          list-files: json
          filters: |
            docs:
              - 'docs/**/*.md'
            added:
              - added: 'docs/**/*.md'
            deleted:
              - deleted: 'docs/**/*.md'
            modified:
              - modified: 'docs/**/*.md'
    
  process_changed_docs_job:
    runs-on: ubuntu-latest
    needs: check_docs_changes
    if: needs.check_docs_changes.outputs.docs_changed == 'true'
    strategy:
      matrix:
        added: ${{ fromJSON(needs.check_docs_changes.outputs.added_files) }}
        modified: ${{ fromJSON(needs.check_docs_changes.outputs.modified_files) }}
        deleted: ${{ fromJSON(needs.check_docs_changes.outputs.deleted_files) }}
    
    steps:
      - name: Print matrix from new process
        run: |
          echo "${{ matrix.added }}"
          echo "${{ matrix.modified }}"
          echo "${{ matrix.deleted }}"
