name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    
    env:
      ENV_IS_ROLLBACK: false
      ENV_TEST_VARIABLE: false
    
    steps:
      - name: Detect changes
        run: |
          page=1
          while true; do
            data=$(curl -s -X GET -G "${{ github.event.pull_request.url }}/files?per_page=100&page=${page}" \
              --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'Accept: application/vnd.github+json' \
              | jq -r '.[]') # | .status + " " + .contents_url + " " + .previous_filename
            [[ $data ]] || break;
            echo "$data" >> output
            echo $data
            ((page++))
          done
          
          sed -i "s/https:\/\/api.github.com//g" output
          sed -i "s/%2F/\//g" output
          
          cat output | while read line 
          do
              if [[ $line == *"docs"*".md"* ]]; then
                echo "$line" >> md_files
              fi
          done
          rm output
          
          cat md_files
