name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.docs-changes.outputs.docs }}
      docs_changes_list: ${{ steps.docs-changes.outputs.docs_files }}
    
    steps:
      - name: Check changed files
        uses: dorny/paths-filter@v2
        id: docs-changes
        with:
          list-files: json
          filters: |
            docs:
              - 'docs/**/*.md'
    
  process_changed_docs_job:
    runs-on: ubuntu-latest
    needs: check_docs_changes
    if: needs.check_docs_changes.outputs.docs_changed == 'true'
    strategy:
      matrix:
        md_file: ${{ fromJSON(needs.check_docs_changes.outputs.docs_changes_list) }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v1
    
      - name: Detect with legacy process
        run: |
          git diff --name-status origin/main | sed 's/\t/__/g' > output
          cat output
          
      - name: set-matrix
        run: echo $(cat output|jq -cnR '[inputs | select(length>0)]')
        
      - name: Sort
        run: |
          cat output | awk -F__ '/^A__/ { print $2 }' 
          cat output | awk -F__ '/^M__/ { print $2 }' 
          cat output | awk -F__ '/^D__/ { print $2 }' 
          
      - name: Print matrix from new process
        run: echo "${{ matrix.md_file }}"
