name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    
    env:
      ENV_IS_ROLLBACK: false
      ENV_TEST_VARIABLE: false
    
    steps:
          
      - name: Replace ref to base
        run: |
          echo "ENV_IS_ROLLBACK=true" >> $GITHUB_ENV

      - name: Show env result
        run: |
          echo ${{ env.ENV_TEST_VARIABLE || env.ENV_IS_ROLLBACK }}
