name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    
    env:
      ENV_IS_ROLLBACK: false
      ENV_TEST_VARIABLE: false
    
    steps:
      - name: Detect changes
        run: |
          page=1
          while true; do
            data=$(curl -s -X GET -G "${{ github.event.pull_request.url }}/files?per_page=100&page=${page}" \
              --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'Accept: application/vnd.github+json' \
              # | jq -r '.[] | .status + " " + .contents_url')
              | jq -r '.[]')
            [[ $data ]] || break;
            echo "$data" >> output
            ((page++))
          done

          cat output
