name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{steps.docs-changes.outputs.changed}}
    
    steps:
      - name: Check changed files
        uses: dorny/paths-filter@v2
        id: docs-changes
        with:
          filters: |
            docs:
              - 'docs/**/*.md'
      
      - name: Write true check result to output
        if: ${{ steps.docs-changes.outputs.docs }} == 'true'
        run: echo "changed=true" >> $GITHUB_OUTPUT
        
      - name: Write false check result to output
        if: ${{ steps.docs-changes.outputs.docs }} == 'false'
        run: echo "changed=false" >> $GITHUB_OUTPUT

  process_changed_docs_job:
    runs-on: ubuntu-latest
    needs: check_docs_changes
    #if: needs.check_docs_changes.outputs.docs_changed == true
    
    steps:
      - name: Print variable
        run: echo ${{needs.check_docs_changes.outputs.docs_changed}}
