name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Show pull-request
        run: |
          data=$(curl -s -X GET -G "${{ github.event.pull_request.url }}/files?per_page=100&page=${page}" \
              --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'Accept: application/vnd.github+json' \
              | jq -r '.[]')
              #| jq -r '.[] | .status + " " + .contents_url')
          echo $data
          
      - name: show base branch
        run: |
          echo ${{ env.GITHUB_BASE_REF }}
