name: Reusable workflow

on: workflow_call

jobs:
  docs_changed_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check changed files
        uses: dorny/paths-filter@v2
        id: docs-changes
        with:
          filters: |
            docs:
              - 'docs/**/*.md'
      
      - name: Start job because docs was changed
        if: steps.docs-changes.outputs.docs == 'true'
        run: echo "Docs was changed"
