name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.docs-changes.outputs.docs }}
      docs_changed_list: ${{ steps.docs-changes.outputs.docs_files }}
      docs_modified_list: ${{ steps.docs-changes.outputs.docs_modified_files }}
      docs_added_list: ${{ steps.docs-changes.outputs.docs_added_files }}
      docs_deleted_list: ${{ steps.docs-changes.outputs.docs_deleted_files }}
    
    steps:
      - name: Check changed files
        uses: dorny/paths-filter@v2
        id: docs-changes
        with:
          list-files: json
          filters: |
            docs:
              - 'docs/**/*.md'
            docs_modified:
              - modified: 'docs/**/*.md'
            docs_added:
              - added: 'docs/**/*.md'   
            docs_deleted:
              - deleted: 'docs/**/*.md'            
    
  process_changed_docs_job:
    runs-on: ubuntu-latest
    needs: check_docs_changes
    if: needs.check_docs_changes.outputs.docs_changed == 'true'
    strategy:
      matrix:
        md_file: ${{ fromJSON(needs.check_docs_changes.outputs.docs_changed_list) }}
    
    steps:
      - name: Debug added files
        run: echo "${{ needs.check_docs_changes.outputs.docs_added_list }}, ${{ matrix.md_file }}, ${{ contains(fromJSON(needs.check_docs_changes.outputs.docs_added_list), matrix.md_file) }}"
    
      - name: Check added files
        if: ${{ contains(fromJSON(needs.check_docs_changes.outputs.docs_added_list), matrix.md_file) == true }}
        run: echo "ENV_OPERATION=add" >> $GITHUB_ENV
        
      - name: Check modified files
        if: ${{ contains(fromJSON(needs.check_docs_changes.outputs.docs_modified_list), matrix.md_file) == true }}
        run: echo "ENV_OPERATION=update" >> $GITHUB_ENV
        
      - name: Check deleted files
        if: ${{ contains(fromJSON(needs.check_docs_changes.outputs.docs_deleted_list), matrix.md_file) == true }}
        run: echo "ENV_OPERATION=delete" >> $GITHUB_ENV
        
      - name: Print info
        run: |
          echo "Operation: ${{ env.ENV_OPERATION }}; File: ${{ matrix.md_file }}"
