name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Show pull-request
        run: |
          page=1
          while true; do
            data=$(curl -s -X GET -G "${{ github.event.pull_request.url }}/files?per_page=100&page=${page}" \
              --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'Accept: application/vnd.github+json' \
              | jq -r '.[] | .status + " " + .contents_url')
            [[ $data ]] || break;
            echo "$data" >> output
            ((page++))
          done
          
          sed -i "s/https:\/\/api.github.com//g" output
          sed -i "s/%2F/\//g" output
          
          echo $(cat output)
          
      - name: Replace ref to base
        run: |
          echo "ENV_FILE_PATH=$(cat output | sed 's/.md?ref=.*/.md?ref=${{ github.event.pull_request.base.ref }}/')" >> $GITHUB_ENV
          echo ${{ env.ENV_FILE_PATH }}
          
