name: Reusable workflow

on: workflow_call

jobs:
  pr_created_job:
    if: github.event.pull_request.created == true
    runs-on: ubuntu-latest
    
    steps:
      - name: PR created
        run: echo "PR created"
#-------------------------------------------------
  pr_merged_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: PR merged
        run: echo "PR merged"
#-------------------------------------------------        
  pr_declined_job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    
    steps:
      - name: PR declined
        run: echo "PR declined"
