name: Reusable workflow

on: workflow_call

jobs:
  anyone_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: PR opened
        run: echo "PR opened"
        
  another_job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    
    steps:
      - name: PR closed
        run: echo "PR closed"
