name: Reusable workflow

on: workflow_call

jobs:
  check_docs_changes:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.docs-changes.outputs.docs }}
      docs_changes_list: ${{ steps.docs-changes.outputs.changes }}
    
    steps:
      - name: Check changed files
        uses: dorny/paths-filter@v2
        id: docs-changes
        with:
          filters: |
            docs:
              - 'docs/**/*.md'

  process_changed_docs_job:
    runs-on: ubuntu-latest
    needs: check_docs_changes
    if: needs.check_docs_changes.outputs.docs_changed == 'true'
    strategy:
      matrix:
        md_files: ${{ fromJSON(needs.check_docs_changes.outputs.docs_changes_list) }}
    
    steps:
      - name: Print md_files
        run: echo md_files
